// build-dictionary fetches English descriptions for OSM tag key=value pairs
// from osm_tags.lua and writes them as CSV to stdout:
//
//	key,value,description
//
// Sources (tried in order for each tag):
//  1. taginfo API  — /api/4/tag/wiki_pages (EN entry)
//  2. OSM Wiki API — Tag:<key>=<value> page, {{ValueDescription|description=…}}
//
// The descriptions originate from the OpenStreetMap Wiki and are licensed under
// Creative Commons Attribution-ShareAlike 2.0 (CC-BY-SA 2.0):
// https://creativecommons.org/licenses/by-sa/2.0/
// The generated CSV is therefore distributed under CC-BY-SA 2.0 as well.
//
// Usage:
//
//	go run ./cmd/build-dictionary [-config path/to/osm_tags.lua] > infra/osm-importer/osm_tags.csv
package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strings"
	"time"

	lua "github.com/Shopify/go-lua"
)

const (
	tagInfoBase   = "https://taginfo.openstreetmap.org/api/4"
	wikiBase      = "https://wiki.openstreetmap.org/w/api.php"
	defaultConfig = "infra/osm-importer/osm_tags.lua"
	topNValues    = 60
	rateDelay     = 300 * time.Millisecond
	httpTimeout   = 15 * time.Second
)

var httpClient = &http.Client{Timeout: httpTimeout}

type tagEntry struct {
	key    string
	values []string // nil = fetch top N from taginfo
}

var descRe = regexp.MustCompile(`(?i)\|description=([^|{}]+)`)

func main() {
	configPath := flag.String("config", defaultConfig, "path to osm_tags.lua")
	outputPath := flag.String("o", "", "output file (default: stdout); written atomically via temp file")
	flag.Parse()

	entries, err := loadConfig(*configPath)
	if err != nil {
		log.Fatalf("load config: %v", err)
	}

	// Choose output: stdout or a temp file that is atomically renamed on success.
	var out io.Writer = os.Stdout
	var tmpPath string
	var tmpFile *os.File
	if *outputPath != "" {
		f, err := os.CreateTemp("", "osm_tags_*.csv")
		if err != nil {
			log.Fatalf("create temp file: %v", err)
		}
		tmpPath = f.Name()
		tmpFile = f
		defer func() {
			// Clean up temp file on failure (if rename didn't happen).
			if tmpPath != "" {
				_ = os.Remove(tmpPath)
			}
		}()
		out = f
	}

	if _, err := fmt.Fprint(out, "# OSM tag descriptions © OpenStreetMap Wiki contributors\n# Licensed under Creative Commons Attribution-ShareAlike 2.0 (CC-BY-SA 2.0)\n# https://creativecommons.org/licenses/by-sa/2.0/\n# Source: https://wiki.openstreetmap.org — generated by cmd/build-dictionary\n"); err != nil {
		log.Fatalf("write header: %v", err)
	}

	w := csv.NewWriter(out)
	if err := w.Write([]string{"key", "value", "description"}); err != nil {
		log.Fatal(err)
	}

	for _, e := range entries {
		values := e.values
		if values == nil {
			var err error
			values, err = fetchTopValues(e.key)
			if err != nil {
				log.Printf("warn: top values for %q: %v", e.key, err)
				continue
			}
			time.Sleep(rateDelay)
		}

		for _, v := range values {
			desc, err := description(e.key, v)
			if err != nil {
				log.Printf("warn: %s=%s: %v", e.key, v, err)
			}
			if err := w.Write([]string{e.key, v, desc}); err != nil {
				log.Fatal(err)
			}
			w.Flush()
			time.Sleep(rateDelay)
		}
	}

	if *outputPath != "" {
		// Close before rename to ensure all OS buffers are flushed.
		if err := tmpFile.Close(); err != nil {
			log.Fatalf("close temp file: %v", err)
		}
		if err := os.Rename(tmpPath, *outputPath); err != nil {
			log.Fatalf("rename %s → %s: %v", tmpPath, *outputPath, err)
		}
		tmpPath = "" // prevent deferred cleanup
		log.Printf("written: %s", *outputPath)
	}
}

// loadConfig executes the Lua file and reads the returned table of tag entries.
// Expected Lua structure:
//
//	return {
//	    { key = "leisure" },
//	    { key = "waterway", values = {"river", "canal"} },
//	    ...
//	}
func loadConfig(path string) ([]tagEntry, error) {
	l := lua.NewState()
	lua.OpenLibraries(l)

	if err := lua.DoFile(l, path); err != nil {
		return nil, fmt.Errorf("execute %s: %w", path, err)
	}

	if l.Top() == 0 || !l.IsTable(-1) {
		return nil, fmt.Errorf("%s: expected table return value", path)
	}

	outerIdx := l.Top() // absolute index of the outer array table

	var entries []tagEntry
	l.PushNil() // initial key for iteration
	for l.Next(outerIdx) {
		// stack: ..., outer_table[outerIdx], key, value(entry table)
		if l.IsTable(-1) {
			if e := readEntry(l); e.key != "" {
				entries = append(entries, e)
			}
		}
		l.Pop(1) // pop value, leave key for next iteration
	}

	return entries, nil
}

// readEntry reads a single { key=..., values={...} } table from the top of the stack.
// It does not pop the entry table itself.
func readEntry(l *lua.State) tagEntry {
	entryIdx := l.Top() // absolute index of the entry table

	var e tagEntry

	l.Field(entryIdx, "key")
	if l.IsString(-1) {
		e.key, _ = l.ToString(-1)
	}
	l.Pop(1)

	l.Field(entryIdx, "values")
	if l.IsTable(-1) {
		valuesIdx := l.Top()
		l.PushNil()
		for l.Next(valuesIdx) {
			if s, ok := l.ToString(-1); ok && s != "" {
				e.values = append(e.values, s)
			}
			l.Pop(1) // pop value, leave key
		}
	}
	l.Pop(1) // pop values table (or nil)

	return e
}

// description tries taginfo first, then OSM Wiki as fallback.
func description(key, value string) (string, error) {
	desc, err := taginfoDescription(key, value)
	if err != nil {
		return "", fmt.Errorf("taginfo: %w", err)
	}
	if desc != "" {
		return desc, nil
	}
	time.Sleep(rateDelay)
	desc, err = wikiDescription(key, value)
	if err != nil {
		log.Printf("warn: wiki fallback for %s=%s: %v", key, value, err)
		return "", nil
	}
	return desc, nil
}

// fetchTopValues returns up to topNValues values for key, ordered by usage count desc.
func fetchTopValues(key string) ([]string, error) {
	u := fmt.Sprintf("%s/key/values?key=%s&sortname=count&sortorder=desc&page=1&rp=%d",
		tagInfoBase, url.QueryEscape(key), topNValues)
	var resp struct {
		Data []struct {
			Value string `json:"value"`
		} `json:"data"`
	}
	if err := getJSON(u, &resp); err != nil {
		return nil, err
	}
	out := make([]string, 0, len(resp.Data))
	for _, d := range resp.Data {
		if d.Value != "" {
			out = append(out, d.Value)
		}
	}
	return out, nil
}

// taginfoDescription returns the EN wiki description from taginfo, or "" if not found.
func taginfoDescription(key, value string) (string, error) {
	u := fmt.Sprintf("%s/tag/wiki_pages?key=%s&value=%s",
		tagInfoBase, url.QueryEscape(key), url.QueryEscape(value))
	var resp struct {
		Data []struct {
			Lang        string `json:"lang"`
			Description string `json:"description"`
		} `json:"data"`
	}
	if err := getJSON(u, &resp); err != nil {
		return "", err
	}
	for _, d := range resp.Data {
		if d.Lang == "en" {
			return d.Description, nil
		}
	}
	return "", nil
}

// wikiDescription fetches the EN description from the OSM Wiki MediaWiki API
// by parsing the {{ValueDescription|description=…}} template in the page wikitext.
func wikiDescription(key, value string) (string, error) {
	title := fmt.Sprintf("Tag:%s=%s", key, value)
	u := fmt.Sprintf("%s?action=parse&page=%s&prop=wikitext&format=json",
		wikiBase, url.QueryEscape(title))
	var resp struct {
		Parse struct {
			Wikitext struct {
				Text string `json:"*"`
			} `json:"wikitext"`
		} `json:"parse"`
		Error struct {
			Code string `json:"code"`
		} `json:"error"`
	}
	if err := getJSON(u, &resp); err != nil {
		return "", err
	}
	if resp.Error.Code == "missingtitle" {
		return "", nil
	}
	m := descRe.FindStringSubmatch(resp.Parse.Wikitext.Text)
	if m == nil {
		return "", nil
	}
	return strings.TrimSpace(m[1]), nil
}

func getJSON(u string, dst any) error {
	resp, err := httpClient.Get(u) //nolint:noctx
	if err != nil {
		return fmt.Errorf("GET %s: %w", u, err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read %s: %w", u, err)
	}
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", u, resp.StatusCode)
	}
	return json.Unmarshal(body, dst)
}
