// Package dictionary provides the OSM tag key=value description table,
// embedded at build time from osm_tags.csv (generated by cmd/build-dictionary).
package dictionary

import (
	"bytes"
	"encoding/csv"
	_ "embed"
	"io"
)

//go:embed osm_tags.csv
var csvData []byte

// Entry is a single row from the dictionary.
type Entry struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description,omitempty"`
}

// Load parses the embedded CSV and returns all entries.
// The CSV has a header row (key,value,description) which is skipped.
func Load() ([]Entry, error) {
	r := csv.NewReader(bytes.NewReader(csvData))
	r.Comment = '#'
	_, _ = r.Read() // skip header
	var entries []Entry
	for {
		row, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if len(row) < 2 {
			continue
		}
		e := Entry{Key: row[0], Value: row[1]}
		if len(row) >= 3 {
			e.Description = row[2]
		}
		entries = append(entries, e)
	}
	return entries, nil
}
